android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.injected.testOnly=false

# Paste your free Last.fm API key here before running the app.
# You can get one from https://www.last.fm/api/account/create
LASTFM_API_KEY=PUT_YOUR_LASTFM_API_KEY_HERE
